# docker-compose.yml
services:
  # ===========================================
  # postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: alias111
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    # outer network
    networks:
      - postgres
    restart: unless-stopped
  # ===========================================
  #  pgadmin
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    # inner network for docker
    networks:
      - postgres
    restart: unless-stopped
  # ===========================================
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - "9411:9411"
# ===========================================
# bridging both postgres instances
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin: