### Send POST request with json body
POST localhost:8080/api/v1/customers
Content-Type: application/json

{
  "firstName": "Feign Test",
  "lastName": "client service in action",
  "email": "feign-package@fei.com"
}