### Send POST request with json body
POST localhost:8080/api/v1/customers
Content-Type: application/json

{
  "firstName": "Eureka",
  "lastName": "Server/Client in action",
  "email": "eureka-package@erk.com"
}