### Send POST request with json body
POST localhost:8080/api/v1/customers
Content-Type: application/json

{
  "firstName": "Sleuth",
  "lastName": "testing id of sleuth",
  "email": "sleuth-package@fei.com"
}