# eureka-server.yml
# ======================================
# spring
spring:
  application:
    name: eureka-server
  # --------------------
  # zipkin
  zipkin:
    base-url: http://localhost:9411
# ======================================
# server
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false







